server:
  port: 8088
  error:
    path: /error
  servlet:
    session:
      persistent: true
      timeout: 48h
spring:
  session:
    jdbc:
      initialize-schema: always
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/camunda?nullCatalogMeansCurrent=true
    username: qwe
    password: qwe
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    # set thymeleaf-prefix to local path for hot html template reload
    # thymeleaf-prefix: file:/d:/files/camunda/src/main/resources/templates/
    thymeleaf-prefix: classpath:/templates/
    base-url: http://127.0.0.1
    name: Camunda example
    shortname: Example
    version: '@project.version@'
    company: Example org
    password-salt: salt
    process-key-default: example_process
camunda:
  bpm:
    metrics:
      enabled: false
      db-reporter-activate: false
logging:
  file: logs/camunda.log
